
###
POST http://localhost:8080/auth
Content-Type: application/json

{
  "nombre": "usuario2",
  "password": "clave123",
  "email": "felisucojvps3@gmail.com"
}
###
GET http://localhost:8080/auth/verificar/QeZqm4ARRMR0iKCdob1E5Q==
###
GET http://localhost:8080/auth?
    nombre=usuario2&password=clave123

###
GET http://localhost:8080/playlist
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c3VhcmlvMiIsImlhdCI6MTczOTcyNjc5NSwiZXhwIjoxNzM5NzMwMzk1fQ.1F8D3Eubis946iALDZh33sEdO2QdNPJ6FTBg6aeFg_E

###
POST http://localhost:8080/playlist
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c3VhcmlvMiIsImlhdCI6MTczOTcyNjc5NSwiZXhwIjoxNzM5NzMwMzk1fQ.1F8D3Eubis946iALDZh33sEdO2QdNPJ6FTBg6aeFg_E

{
  "nombre": "Kyoto",
  "artista": "Skrillex"
}

###
PUT http://localhost:8080/playlist/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c3VhcmlvMiIsImlhdCI6MTczOTcyNjc5NSwiZXhwIjoxNzM5NzMwMzk1fQ.1F8D3Eubis946iALDZh33sEdO2QdNPJ6FTBg6aeFg_E

{
  "nombre": "Don't Stop Me Now",
  "artista": "Queen"
}

###
DELETE http://localhost:8080/playlist/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c3VhcmlvMiIsImlhdCI6MTczOTcyNjYxOSwiZXhwIjoxNzM5NzMwMjE5fQ.Vvwh1v13Fk0tKis6fDcYc11Emgsosf6BDsTNXARdVjQ

